pip install wheel
pip install pip
pip install sodapy
pip install numpy
pip install pandas
pip install shapely
pip install gdal
pip install fiona
pip install pyproj
pip install six
pip install rtree
pip install geopandas
